############# English navigation ##############

# main menu
[[main]]
name = "Send Via API"
url = "/"
weight = 1

[[main]]
name = "Send Via SMTP"
url = "send-via-smtp/"
weight = 2

[[main]]
name = "Pricing"
url = "pricing/"
weight = 3

[[main]]
name = "Contact"
url = "contact/"
weight = 4

[[main]]
name = "Documentation"
url = "documentation/"
weight = 5

[[main]]
name = "API"
url = "api/"
weight = 6


# footer menu quick links
[[quick_links]]
name = "Send Via API"
url = "/"
weight = 1

[[quick_links]]
name = "Send Via SMTP"
url = "send-via-smtp/"
weight = 2

[[quick_links]]
name = "Pricing"
url = "pricing/"
weight = 3


[[quick_links]]
name = "Contact"
url = "contact/"
weight = 4

[[quick_links]]
name = "Documentation"
url = "/documentation/introduction/readme"
weight = 4

[[legal]]
name = "Privacy Policy"
url = "/privacy-policy/"
weight = 1

[[legal]]
name = "Terms and Conditions"
url = "/terms-and-conditions/"
weight = 2